_target_: pytorch_lightning.Trainer
strategy: "ddp_find_unused_parameters_true"
accumulate_grad_batches: 4
min_epochs: 1
max_epochs: 200
deterministic: true
accelerator: gpu
devices: -1
#auto_select_gpus: true
check_val_every_n_epoch: 1
default_root_dir: .
profiler: false
