defaults:
    - _self_
    - datamodule: default
    - model: default
    - trainer: allgpus
    - experiment: null

seed: 6473628
name: default  # experiment name
train: true
test: false
resume_from_checkpoint: "/home/ab2810/rds/hpc-work/FastGenSep/seed_checkpoint/epoch-030_si_sdr-6.211.ckpt"

path:
    exp_root: exp
    datasets:
        wsj0_mix: 
        valentini: 
        libri_mix: /home/ab2810/rds/hpc-work/LibriMix
    figures: figures
    
hydra:
    run:
        dir: ${path.exp_root}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
    job:
        config:
            override_dirname:
                kv_sep: '-'
                item_sep: '_'
                exclude_keys: 
                    - path.exp_root
