_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 50
                - 55
                - 63
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 50
                - 55
                - 63
                - 103
            "3":
                - 13
                - 23
                - 35
                - 55
            "4": 3.10.13
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
